---
abstract: 'connect to Apache Tika'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  Data::Dumper: '0'
  ExtUtils::MakeMaker: '0'
  File::Basename: '0'
  File::Copy: '0'
  File::Find: '0'
  File::Path: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.44, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Apache-Tika-Async
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Exporter: '5'
  Future: '0'
  JSON::XS: '0'
  LWP::UserAgent: '6'
  Moo: '2'
  Try::Tiny: '0'
  perl: '5.020'
resources:
  license: https://dev.perl.org/licenses/
  repository: git://github.com/Corion/Apache-Tika-Async.git
version: '0.09'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
